'use client';

import { useEffect, useRef, useState } from 'react';
import { ArrowUpRight, ArrowRight, Check, ChevronLeft, Upload, X, Play, Pause, Sparkles, ImagePlus, Film, Volume2, Link as LinkIcon, CheckCircle2, Coffee, Cookie, Croissant, LoaderCircle, RotateCcw, Menu } from 'lucide-react';

type Product = { name: string; category: string; feature: string; image: string; kind: string };
const initial: Product = { name: '오늘의 커피', category: '음료', feature: '바쁜 하루에 잠깐의 여유를 주는 부드러운 커피', image: '', kind: 'coffee' };
const moods = ['유머', '감동', '행복'];
const icons = [Coffee, Croissant, Cookie];
const samples = ['커피', '빵', '과자'];
const tasks = ['상품을 살펴보고 있어요', '상품 레퍼런스를 정리하고 있어요', '이야기에 필요한 장면을 준비하고 있어요', '30초의 이야기를 만들고 있어요'];
function ProductArt({ product, className = '' }: { product: Product; className?: string }) {
  if (product.image) return <img className={`product-image ${className}`} src={product.image} alt={product.name} />;
  if (product.kind === 'bread') return <div className={`bread-art ${className}`} aria-label="빵 일러스트"><span/><span/><span/></div>;
  if (product.kind === 'cookie') return <div className={`cookie-art ${className}`} aria-label="쿠키 일러스트">●<i>●</i><b>●</b><em>●</em></div>;
  return <div className={`cup-art ${className}`} aria-label="커피컵 일러스트"><div className="cup-lid"/><div className="cup-body"><span>little<br/>daily.</span><small>A MOMENT FOR YOU</small></div></div>;
}
export default function Home() {
  const [step, setStep] = useState(0);
  const [product, setProduct] = useState<Product>(initial);
  const [role, setRole] = useState('hero');
  const [mood, setMood] = useState(0);
  const [progress, setProgress] = useState(0);
  const [error, setError] = useState('');
  const [notice, setNotice] = useState('');
  const [playing, setPlaying] = useState(false);
  const [elapsed, setElapsed] = useState(0);
  const [saved, setSaved] = useState(false);
  const [menu, setMenu] = useState(false);
  const input = useRef<HTMLInputElement>(null);
  const titles = [`${product.name}, 오늘은 네가 출근해`, '말하지 않아도 전해지는 마음', '행복은 생각보다 가까이에'];
  const plots = role === 'hero' ? [`지친 주인공 대신 출근에 나선 ${product.name}. 모두가 기다린 건 뜻밖에도 이 작은 상품이었다.`, `유난히 긴 하루 끝, 누군가 조용히 건넨 ${product.name}. 작은 배려 하나가 하루의 표정을 바꾼다.`, `거창한 계획 없이 시작한 오후. ${product.name} 하나를 나누는 순간, 평범한 시간이 작은 축제가 된다.`] : [`사무실 모두가 기다리는 특별한 지원군. 거창한 등장 음악 끝에 문이 열리고, 나타난 주인공은 ${product.name}.`, `말없이 서로를 챙겨 온 두 사람. 지친 하루 끝에 놓인 작은 봉투를 열자 ${product.name}와 고맙다는 쪽지가 나타난다.`, `친구들이 몰래 준비한 작은 모임. 마지막 빈자리를 채운 ${product.name} 하나로 평범한 오후가 축제가 된다.`];
  useEffect(() => { try { const raw = localStorage.getItem('story-result'); if (raw) { setSaved(true); if (location.hash === '#result') { const data = JSON.parse(raw); setProduct(data.product); setMood(data.mood); setRole(data.role); setStep(4); } } } catch {} }, []);
  useEffect(() => { if (step !== 3) return; const timer = setInterval(() => setProgress(p => Math.min(100, p + 4)), 240); return () => clearInterval(timer); }, [step]);
  useEffect(() => { if (step === 3 && progress === 100) { setStep(4); try { localStorage.setItem('story-result', JSON.stringify({ product, mood, role })); setSaved(true); } catch { setNotice('브라우저 저장 공간이 부족해 결과가 저장되지 않았어요.'); } } }, [progress, step, product, mood, role]);
  useEffect(() => { if (!playing) return; const timer = setInterval(() => setElapsed(t => { if (t >= 29) { setPlaying(false); return 30; } return t + 1; }), 1000); return () => clearInterval(timer); }, [playing]);
  useEffect(() => { if (!notice) return; const timer = setTimeout(() => setNotice(''), 4000); return () => clearTimeout(timer); }, [notice]);
  function start() { setStep(1); setError(''); window.scrollTo({ top: 0, behavior: 'smooth' }); }
  function upload(file?: File) { if (!file) return; if (!['image/jpeg', 'image/png', 'image/webp'].includes(file.type)) { setError('JPG, PNG, WEBP 사진을 선택해 주세요.'); return; } if (file.size > 10 * 1024 * 1024) { setError('10MB 이하의 사진을 선택해 주세요.'); return; } const reader = new FileReader(); reader.onload = () => { setProduct(p => ({ ...p, image: String(reader.result), name: '', feature: '' })); setError(''); }; reader.readAsDataURL(file); }
  function restore() { try { const raw = localStorage.getItem('story-result'); if (!raw) { setNotice('아직 만든 이야기가 없어요. 첫 이야기를 만들어 보세요.'); return; } const data = JSON.parse(raw); setProduct(data.product); setMood(data.mood); setRole(data.role); setStep(4); setElapsed(0); } catch { setNotice('저장된 결과를 불러오지 못했어요.'); } }
  async function copy() { try { await navigator.clipboard.writeText(`${location.origin}/#result`); setNotice('목업 결과 링크를 복사했어요. 이 브라우저에서만 복원됩니다.'); } catch { setNotice('링크 복사를 지원하지 않는 환경이에요. 주소 뒤에 #result를 붙여 저장해 주세요.'); } }
  return <><header className="header"><a className="logo" href="/" aria-label="STory 홈">STory<span>®</span></a><nav className={menu ? 'open' : ''}><button onClick={() => { setStep(0); setMenu(false); }}>스튜디오</button><button onClick={() => { setStep(0); setTimeout(() => document.getElementById('how')?.scrollIntoView({ behavior: 'smooth' }), 50); setMenu(false); }}>만드는 과정</button><button onClick={restore}>내 이야기 {saved && <i className="saved-dot"/>}</button></nav><button className="header-cta" onClick={start}>이야기 만들기 <ArrowUpRight size={16}/></button><button className="mobile-menu" aria-label="메뉴 열기" onClick={() => setMenu(!menu)}><Menu/></button></header>
  <main>{step === 0 ? <>
    <section className="hero"><div className="hero-copy"><div className="eyebrow"><span/> A LITTLE PRODUCT. A BIG STORY.</div><h1>당신의 상품에,<br/><span>이야기를.</span><i>✳</i></h1><p>커피 한 잔도, 작은 과자 하나도.<br/>사진 한 장이면 마음을 움직이는 30초 광고가 됩니다.</p><button className="primary" onClick={start}>내 상품으로 이야기 만들기 <ArrowUpRight size={21}/></button><div className="hero-meta"><span><Check size={14}/> 사진 한 장으로 시작</span><span><Check size={14}/> 나만의 30초 광고</span></div></div><div className="hero-art"><div className="art-grid"/><div className="art-top"><span>STORY NO. 001</span><span>MADE FROM AN EVERYDAY MOMENT</span></div><span className="floating-tag tag-one"><span className="red-dot"/> 평범한 커피 한 잔이</span><div className="hero-cup"><ProductArt product={initial}/></div><div className="orbit"/><span className="art-star">✳</span><span className="floating-tag tag-two">누군가의 하루를 바꾸는 이야기로 <Sparkles size={15}/></span><div className="art-bottom"><span>YOUR PRODUCT,<br/><b>THE MAIN CHARACTER.</b></span><button onClick={() => { setProduct(initial); setMood(1); setStep(4); }} aria-label="커피 샘플 미리보기"><Play size={20} fill="currentColor"/></button><span className="duration">00:30<br/><small>VERTICAL FILM</small></span></div></div></section>
    <div className="ticker"><span>EVERY PRODUCT HAS A STORY</span><span>✳</span><span>당신의 일상을, 한 편의 광고로</span><span>✳</span><span>MADE TO MAKE YOU FEEL</span><span>✳</span></div>
    <section className="how section" id="how"><div className="section-heading"><div><span className="eyebrow muted">FROM PHOTO TO FILM</span><h2>시작은 가볍게. 이야기는 특별하게.</h2></div><p>복잡한 편집도, 긴 설명도 필요 없어요.<br/>이야기의 주인공만 준비해 주세요.</p></div><div className="process-grid">{[{ icon: ImagePlus, title: '상품을 보여주세요', desc: '커피, 빵, 과자. 사진을 올리고\n상품의 매력을 한 줄로 알려주세요.' }, { icon: Sparkles, title: '마음에 드는 이야기를 골라요', desc: '유머, 감동, 행복 중\n내 상품과 어울리는 서사를 선택하세요.' }, { icon: Film, title: '30초의 광고가 완성돼요', desc: '상품이 이야기 속으로 들어갑니다.\n완성된 순간을 저장하고 나눠보세요.' }].map((item, i) => <div className="process" key={item.title}><div className="process-top"><item.icon size={25} strokeWidth={1.5}/><span>0{i + 1}</span></div><h3>{item.title}</h3><p>{item.desc}</p></div>)}</div></section>
    <section className="samples section"><div className="section-heading"><div><span className="eyebrow muted">SMALL THINGS, GREAT STORIES</span><h2>어떤 상품으로 시작할까요?</h2></div><span className="sample-caption">가까이에 있는 것부터, 가볍게.</span></div><div className="sample-grid">{samples.map((name, i) => <button key={name} className={`sample sample-${i}`} onClick={() => { setProduct({ ...initial, name, kind: ['coffee', 'bread', 'cookie'][i], category: i ? '간식' : '음료', feature: '' }); start(); }}><span>0{i + 1} / {['A DAILY PAUSE', 'A WARM MOMENT', 'A LITTLE JOY'][i]}</span><ProductArt product={{ ...initial, kind: ['coffee', 'bread', 'cookie'][i] }}/><div><h3>{name}</h3><ArrowUpRight/></div></button>)}</div></section>
    <section className="bottom-cta"><span>YOUR NEXT STORY STARTS HERE</span><h2>작은 상품의 큰 가능성.</h2><button className="dark-button" onClick={start}>첫 이야기 시작하기 <ArrowUpRight size={18}/></button></section>
  </> : <section className="workspace"><div className="work-top"><button className="back" onClick={() => { setPlaying(false); setStep(step === 4 || step === 3 ? 0 : step - 1); }}><ChevronLeft size={17}/>{step > 2 ? '스튜디오로' : '이전으로'}</button><span className="mock-label">INTERACTIVE DEMO · 실제 AI 호출 없음</span></div><div className="steps">{['상품 준비', '이야기 선택', '광고 제작'].map((label, i) => <div className={step >= i + 1 ? 'active' : ''} key={label}><span>{step > i + 1 ? <Check size={13}/> : `0${i + 1}`}</span>{label}</div>)}</div>
    {step === 1 && <><div className="work-heading"><span className="eyebrow muted">MEET YOUR MAIN CHARACTER</span><h1>어떤 상품의 이야기를 만들까요?</h1><p>사진 한 장과 작은 특징 하나면 충분해요.</p></div><div className="form-grid"><div><button className={`upload-zone ${product.image ? 'has-image' : ''}`} onClick={() => input.current?.click()} onDragOver={e => e.preventDefault()} onDrop={e => { e.preventDefault(); upload(e.dataTransfer.files[0]); }}><ProductArt product={product}/><div className="upload-caption"><Upload size={19}/><strong>{product.image ? '다른 사진으로 바꾸기' : '상품 사진을 올려주세요'}</strong><span>눌러서 선택하거나 사진을 끌어 놓으세요</span><small>JPG, PNG, WEBP · 최대 10MB</small></div></button><input ref={input} type="file" accept="image/jpeg,image/png,image/webp" hidden onChange={e => upload(e.target.files?.[0])}/><div className="demo-picks"><span>사진이 없다면</span>{samples.map((name, i) => { const Icon = icons[i]; return <button key={name} onClick={() => setProduct({ ...initial, name, kind: ['coffee', 'bread', 'cookie'][i], category: i ? '간식' : '음료', feature: '' })}><Icon size={15}/>{name}</button>; })}</div><p className="field-note">목업에서는 원본 사진을 미리 보여드려요. 배경 제거와 상품 분석은 실제 서비스에서 연결됩니다.</p></div><div className="form-fields"><span className="panel-label">PRODUCT DETAILS</span><label>상품명 <span>*</span><input maxLength={40} value={product.name} placeholder="예: 오늘의 아이스 라떼" onChange={e => setProduct({ ...product, name: e.target.value })}/></label><label>상품 종류<select value={product.category} onChange={e => setProduct({ ...product, category: e.target.value })}><option>음료</option><option>빵·베이커리</option><option>간식</option></select></label><label>강조하고 싶은 매력 한 줄 <span>*</span><textarea maxLength={120} value={product.feature} placeholder="예: 고소한 우유와 부드러운 커피가 주는 잠깐의 여유" onChange={e => setProduct({ ...product, feature: e.target.value })}/><small className="char-count">{product.feature.length} / 120</small></label><label>이야기 속 상품의 역할</label><div className="role-options"><button className={role === 'hero' ? 'selected' : ''} onClick={() => setRole('hero')}><strong>처음부터 주인공</strong><small>상품을 중심으로 펼쳐지는 이야기</small></button><button className={role === 'twist' ? 'selected' : ''} onClick={() => setRole('twist')}><strong>마지막에 깜짝 등장</strong><small>반전과 해결책이 되는 상품</small></button></div>{error && <p role="alert" className="error">{error}</p>}<button className="primary full" onClick={() => { if (!product.name.trim() || !product.feature.trim()) { setError('상품명과 강조할 특징 한 줄을 입력해 주세요.'); return; } setError(''); setStep(2); window.scrollTo(0, 0); }}>이야기 만나보기 <ArrowRight size={19}/></button></div></div></>}
    {step === 2 && <><div className="work-heading"><span className="eyebrow muted">CHOOSE YOUR STORY</span><h1>어떤 마음을 전하고 싶나요?</h1><p><b>{product.name}</b>의 서로 다른 세 가지 이야기. 가장 끌리는 한 편을 골라주세요.</p></div><div className="story-grid">{moods.map((name, i) => <button className={`story-card story-${i} ${mood === i ? 'selected' : ''}`} key={name} onClick={() => setMood(i)}><div className="story-visual"><span>{['HA!', 'FOR YOU', 'OH, HAPPY'][i]}</span><i>{['✷', '♡', '☀'][i]}</i><div className="choice-check">{mood === i && <Check size={16}/>}</div></div><div className="story-content"><span className="mood-tag">{name} / 30 SEC</span><h2>{titles[i]}</h2><p>{plots[i]}</p><div className="memory"><small>마지막에 남는 상품의 인상</small><strong>{['하루를 구하는 유쾌한 파트너', '마음을 대신 전하는 작은 선물', '일상 속 행복을 나누는 매개체'][i]}</strong></div></div></button>)}</div><div className="selection-bar"><p><b>{moods[mood]}</b> · {role === 'hero' ? '상품이 주인공인 이야기' : '마지막에 상품이 등장하는 이야기'}<small>이야기와 제작 과정은 준비된 목업 데이터로 시연됩니다.</small></p><button className="primary" onClick={() => { setProgress(0); setStep(3); window.scrollTo(0, 0); }}>이 이야기로 광고 만들기 <ArrowRight size={19}/></button></div></>}
    {step === 3 && <div className="generation"><div className="generation-art"><ProductArt product={product}/><span className="spin-spark">✳</span></div><span className="eyebrow muted">A STORY IS COMING TO LIFE</span><h1>작은 상품이, 큰 이야기가 되는 중.</h1><p>{tasks[Math.min(3, Math.floor(progress / 25))]}</p><div className="progress-track"><span style={{ width: `${progress}%` }}/></div><div className="progress-meta"><span>목업 제작 시뮬레이션</span><b>{progress}%</b></div><div className="generation-note"><LoaderCircle className="spinner" size={18}/>실제 영상 생성 없이 체험용 결과 화면으로 연결됩니다.</div></div>}
    {step === 4 && <><div className="work-heading"><span className="eyebrow muted">YOUR LITTLE BIG STORY</span><h1>당신의 상품이, 이야기의 주인공으로.</h1><p>완성 화면을 미리 체험해 보세요.</p></div><div className="result-grid"><div className={`film-preview mood-${mood} ${playing ? 'is-playing' : ''}`}><span className="film-label">STORYBOARD PREVIEW · 영상 아님</span><div className="film-caption"><small>{['SCENE 01 · 시작', 'SCENE 02 · 전환', 'SCENE 03 · 여운'][Math.min(2, Math.floor(elapsed / 10))]}</small><h2>{elapsed < 10 ? '평범했던 오늘,' : elapsed < 20 ? '작은 순간이 바꾼' : '당신의 하루.'}</h2></div><ProductArt product={product}/><p className="film-subtitle">{elapsed < 10 ? product.feature : elapsed < 20 ? plots[mood] : `${product.name}, ${['유쾌한 하루의 시작', '작은 마음을 전해요', '행복을 나누는 순간'][mood]}`}</p><div className="film-controls"><button onClick={() => { if (elapsed === 30) setElapsed(0); setPlaying(!playing); }} aria-label={playing ? '미리보기 일시정지' : '스토리보드 미리보기 재생'}>{playing ? <Pause size={19}/> : <Play size={19}/>}</button><span>00:{String(elapsed).padStart(2, '0')} / 00:30</span><div/><Volume2 size={17}/></div></div><div className="result-copy"><span className="mood-tag">{moods[mood]} · 세로형 · 30초</span><h2>{titles[mood]}</h2><p>{plots[mood]}</p><div className="result-details"><span>주인공<b>{product.name}</b></span><span>상품의 역할<b>{role === 'hero' ? '처음부터 주인공' : '마지막에 깜짝 등장'}</b></span><span>영상 구성<b>한국어 자막 · 음악 · 내레이션</b></span></div><div className="info-box">현재는 프론트엔드 목업입니다. 미리보기는 무음 스토리보드이며, AI 영상 생성·배경 제거·영상 다운로드는 연결되어 있지 않습니다.</div><button className="primary full" onClick={copy}><LinkIcon size={17}/> 결과 링크 복사</button><p className="field-note">이 브라우저의 저장 데이터로 복원됩니다. 다른 기기 공유는 백엔드 연결 후 지원됩니다.</p><button className="secondary full" onClick={() => { setPlaying(false); setElapsed(0); start(); }}><RotateCcw size={16}/> 다른 이야기 만들기</button></div></div></>}
  </section>}</main><footer><a className="logo" href="/">STory<span>®</span></a><p>작은 상품에서 시작하는, 마음에 남는 이야기.</p><span>© 2026 STory Studio</span><small>프론트엔드 체험 버전</small></footer>{notice && <div className="toast" role="status"><CheckCircle2 size={18}/>{notice}<button onClick={() => setNotice('')} aria-label="알림 닫기"><X size={15}/></button></div>}</>;
}
